test husky

diff --git a/digidex/.husky/pre-commit b/digidex/.husky/pre-commit
--- a/digidex/.husky/pre-commit
+++ b/digidex/.husky/pre-commit
@@ -1,9 +1,7 @@
-echo "Check for linting errors..."
+echo 'Check for linting errors...'
+npm run check:fix || 
+(echo 'Linting errors or tests failed. Please fix them before commiting.' && exit 1)
 
-npm run check:fix ||
-(echo "Linting erros or tests falied. Please fix them before commiting." && exit 1)
 
-npm run check ||
-(echo "Linting erros or tests falied. Please fix them before commiting." && exit 1)
 
-echo "Done"
+echo 'Done'
